name: release

on:
  push:
    tags:
      - '*'

jobs:
  build-contribs:
    name: Build contribs

    steps:
      - uses: actions/checkout@v3
      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: dmd-latest

      - name: Build
        run: dub build --build=release

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: contribs
          artifactErrorsFailBuild: true

    runs-on: ubuntu-latest
